// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbgen

import (
	"time"
)

type Task struct {
	ID              string
	Type            string
	Payload         *string
	Status          string
	StatusUpdatedAt time.Time
	Attempts        int32
	CreatedBy       string
	CreatedAt       time.Time
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	LastLoginAt  time.Time
	CreatedAt    time.Time
}
